spring:
  application:
    name: challenge-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    baseline-on-migrate: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
  group-configs:
    - group: challenge-api
      paths-to-match: /**

logging:
  level:
    root: INFO
    com.example.challenge: DEBUG
    org.springframework.cache: TRACE
    org.springframework.web: INFO 

percentage:
  service:
    url: http://localhost:1080/percentage 
