name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Build Docker image
      run: docker build -t challenge-backend .

    # Nota: Para desplegar la imagen en DockerHub, descomentar y configurar los secretos
    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #
    # - name: Push to DockerHub
    #   run: |
    #     docker tag challenge-backend ${{ secrets.DOCKERHUB_USERNAME }}/challenge-backend:latest
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/challenge-backend:latest 